param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "E:\SetUp\IAR\common\bin\cspybat" -f "E:\CONG VIEC\2018\Thang 2_2018\MH_DA_MACH HEN GIO RELAY_ANH HUNG\SOFTWARE\MH_DA_CODE_MACH HEN GIO RELAY\settings\MH_DA_Form STM8S.Debug.general.xcl" --backend -f "E:\CONG VIEC\2018\Thang 2_2018\MH_DA_MACH HEN GIO RELAY_ANH HUNG\SOFTWARE\MH_DA_CODE_MACH HEN GIO RELAY\settings\MH_DA_Form STM8S.Debug.driver.xcl" 
}
else
{
& "E:\SetUp\IAR\common\bin\cspybat" -f "E:\CONG VIEC\2018\Thang 2_2018\MH_DA_MACH HEN GIO RELAY_ANH HUNG\SOFTWARE\MH_DA_CODE_MACH HEN GIO RELAY\settings\MH_DA_Form STM8S.Debug.general.xcl" --debug_file=$debugfile --backend -f "E:\CONG VIEC\2018\Thang 2_2018\MH_DA_MACH HEN GIO RELAY_ANH HUNG\SOFTWARE\MH_DA_CODE_MACH HEN GIO RELAY\settings\MH_DA_Form STM8S.Debug.driver.xcl" 
}
